version: "3.9"

services:

  postgres:
    build:
      context: "."
      dockerfile: docker/postgres/Dockerfile

    environment:
      POSTGRES_DB: nimbus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
      build:
        context: "."
        dockerfile: docker/tomcat/Dockerfile
      container_name: nimbus-backend
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nimbus
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      restart: always


volumes:
  postgres_data:


