spring.application.name=backend

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nimbus
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway Configuration
spring.flyway.enabled=true